# Generated by Django 2.0.1 on 2018-07-05 15:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0006_courseorg_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='行业')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '行业',
                'verbose_name_plural': '行业',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('sx', '实习岗位'), ('xz', '校招岗位'), ('sz', '社招岗位')], default='sx', max_length=50, verbose_name='职位类型')),
                ('depart', models.CharField(max_length=50, verbose_name='部门')),
                ('title', models.CharField(max_length=30, verbose_name='岗位')),
                ('requirement', models.TextField(verbose_name='岗位要求')),
                ('responsibility', models.TextField(verbose_name='岗位职责')),
                ('work_method', models.TextField(verbose_name='工作方式')),
                ('contact', models.CharField(max_length=30, verbose_name='联系方式')),
                ('source', models.CharField(max_length=30, verbose_name='信息来源')),
                ('append', models.TextField(verbose_name='备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('comment', models.TextField(verbose_name='贝睿点评')),
                ('recommend_level', models.FloatField(default=0.0, verbose_name='推荐指数')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CityDict', verbose_name='所在城市')),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位',
            },
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='机构名')),
                ('address', models.CharField(max_length=100, verbose_name='总部地址')),
                ('tags', models.TextField(max_length=500, verbose_name='机构标签')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('image', models.ImageField(upload_to='org/%Y/%m', verbose_name='Logo')),
                ('introduction', models.TextField(verbose_name='机构简介')),
            ],
            options={
                'verbose_name': '招聘机构',
                'verbose_name_plural': '招聘机构',
            },
        ),
        migrations.AddField(
            model_name='jobs',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Recruiter', verbose_name='机构名称'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.IndustryDict', verbose_name='行业'),
        ),
    ]
