# Generated by Django 2.0.1 on 2018-07-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobs_click_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='click_num',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
    ]
