# Generated by Django 2.0.1 on 2018-07-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_recruiter_click_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='collect_num',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
    ]
