# Generated by Django 2.0.1 on 2018-07-06 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_courseorg_tag'),
        ('jobs', '0004_recruiter_collect_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organization.CityDict', verbose_name='总部城市'),
        ),
    ]
