# Generated by Django 2.0.1 on 2018-07-06 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_recruiter_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobs.IndustryDict', verbose_name='所属行业'),
        ),
    ]
