# Generated by Django 2.0.1 on 2018-07-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_recruiter_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='br_comment',
            field=models.TextField(default='', verbose_name='贝睿点评'),
        ),
    ]
