# Generated by Django 2.0.1 on 2018-09-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_companycomments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobs',
            options={'verbose_name': '在线职位', 'verbose_name_plural': '在线职位'},
        ),
    ]
