# Generated by Django 2.0.1 on 2018-10-15 19:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20180919_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycomments',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='部门'),
        ),
        migrations.AddField(
            model_name='companycomments',
            name='gender_structure',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='性别结构'),
        ),
        migrations.AddField(
            model_name='companycomments',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.IndustryDict', verbose_name='行业'),
        ),
        migrations.AddField(
            model_name='companycomments',
            name='is_in_service',
            field=models.BooleanField(default=False, verbose_name='是否在职'),
        ),
        migrations.AddField(
            model_name='companycomments',
            name='job',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='岗位'),
        ),
        migrations.AddField(
            model_name='companycomments',
            name='job_benifit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='福利待遇'),
        ),
        migrations.AddField(
            model_name='companycomments',
            name='job_culture_env_rating',
            field=models.IntegerField(default=0, verbose_name='工作文化氛围评分'),
        ),
        migrations.AddField(
            model_name='companycomments',
            name='job_env_rating',
            field=models.IntegerField(default=0, verbose_name='工作环境评分'),
        ),
        migrations.AddField(
            model_name='companycomments',
            name='job_payment',
            field=models.IntegerField(default=0, verbose_name='税前月薪'),
        ),
        migrations.AddField(
            model_name='companycomments',
            name='job_strength_rating',
            field=models.IntegerField(default=0, verbose_name='工作强度评分'),
        ),
        migrations.AddField(
            model_name='companycomments',
            name='job_time',
            field=models.IntegerField(default=1, verbose_name='工作年限'),
        ),
        migrations.AddField(
            model_name='companycomments',
            name='job_turnover',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='流失率'),
        ),
        migrations.AddField(
            model_name='companycomments',
            name='job_type',
            field=models.IntegerField(choices=[(0, '实习'), (1, '实习')], default=0, verbose_name='岗位类型'),
        ),
        migrations.AddField(
            model_name='companycomments',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='行业地位'),
        ),
        migrations.AddField(
            model_name='companycomments',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='总评分'),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='founding_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='成立时间'),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='legal_person',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='法人'),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='website',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='主页地址'),
        ),
        migrations.AlterField(
            model_name='companycomments',
            name='comments',
            field=models.CharField(default='', max_length=1000, verbose_name='评论'),
        ),
    ]
