# Generated by Django 2.0.1 on 2018-06-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20180615_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher_tell',
            field=models.CharField(default='按时交作业', max_length=300, verbose_name='老师告诉你'),
        ),
    ]
