# Generated by Django 2.0.1 on 2018-10-15 18:13

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('author', models.CharField(max_length=50, verbose_name='作者')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='article/%Y/%m', verbose_name='封面图')),
                ('abstract', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='摘要')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('like_nums', models.IntegerField(default=0, verbose_name='点赞数')),
                ('category', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='文章类别')),
                ('tag', models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='文章标签')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
